In [1]:
# ------------------------------------------------
# example_usage.ipynb
# shubha07m
# 2024-02-05
# example_usage file shows example of using inputs_to_dataset 
# and inputs_to_dataset_pf functions to generate patches
# ------------------------------------------------

In [2]:
# Importing the required library #
from dataset_extract import inputs_to_dataset, inputs_to_dataset_pf 
import numpy as np

[NbConvertApp] Converting notebook dataset_extract.ipynb to script
[NbConvertApp] Writing 6001 bytes to dataset_extract.py


In [3]:
# Defining the input image, mask, and other parameters#

image = np.array([[[ 1,  2,  3],[ 4,  5,  6], [ -1, 8,  9]],
                 [[ 10,  11,  12], [ 13,  14,  15], [ 16,  17,  18]],
                 [[ 19,  20,  21], [ 22,  23,  24],[25,  26,  27]]])

mask = np.array(
       [[1, 4, 7],
       [10, 4, 16],
       [19, 22, 255]])

stride_length = 1
patch_size = 2

## Example for showing custom patch generation using inputs_to_dataset: without using patchify ##

In [4]:
print("this is the image:\n")
print(image)
print("\n")
print("this is the image patch:\n")
print(inputs_to_dataset(image, mask, patch_size,stride_length)[0])
print("\n")
print("this is the mask:\n")
print(mask)
print("\n")
print("this is the mask patch:\n")
print(inputs_to_dataset(image, mask, patch_size,stride_length)[1])

this is the image:

[[[ 1  2  3]
  [ 4  5  6]
  [-1  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


this is the image patch:

[[[[ 1  2  3]
   [ 4  5  6]]

  [[10 11 12]
   [13 14 15]]]


 [[[10 11 12]
   [13 14 15]]

  [[19 20 21]
   [22 23 24]]]


 [[[13 14 15]
   [16 17 18]]

  [[22 23 24]
   [25 26 27]]]]


this is the mask:

[[  1   4   7]
 [ 10   4  16]
 [ 19  22 255]]


this is the mask patch:

[[[  1   4]
  [ 10   4]]

 [[ 10   4]
  [ 19  22]]

 [[  4  16]
  [ 22 255]]]


## Example for showing custom patch generation using inputs_to_dataset: using patchify package ##

In [5]:
print("this is the image:\n")
print(image)
print("\n")
print("this is the image patch:\n")
print(inputs_to_dataset_pf(image, mask, patch_size,stride_length)[0])
print("\n")
print("this is the mask:\n")
print(mask)
print("\n")
print("this is the mask patch:\n")
print(inputs_to_dataset_pf(image, mask, patch_size,stride_length)[1])

this is the image:

[[[ 1  2  3]
  [ 4  5  6]
  [-1  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


this is the image patch:

[[[[ 1  2  3]
   [ 4  5  6]]

  [[10 11 12]
   [13 14 15]]]


 [[[10 11 12]
   [13 14 15]]

  [[19 20 21]
   [22 23 24]]]


 [[[13 14 15]
   [16 17 18]]

  [[22 23 24]
   [25 26 27]]]]


this is the mask:

[[  1   4   7]
 [ 10   4  16]
 [ 19  22 255]]


this is the mask patch:

[[[  1   4]
  [ 10   4]]

 [[ 10   4]
  [ 19  22]]

 [[  4  16]
  [ 22 255]]]
